baseURL = "https://davideoggioni.dev/"
languageCode = "en-us"
title = "Davide Oggioni"
theme = "cactus"

[params]
colortheme = "light" #dark, classic, white
description = "Ciao! I'm Davide. I'm interested in Programming, Cycling and Bitcoin."
mainSection = "posts"
showAllPostsOnHomePage=true
mainSectionTitle = "Blog"
#tagsOverview = true
mathjax = true # just in case, you know...

[[params.social]]
name = "github"
link = "https://github.com/daviogg"

[[params.social]]
name = "twitter"
link = "https://twitter.com/daviogg"

[[params.social]]
name = "email"
link = "daviogg@protonmail.com"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4